### PR TITLE
generate demos using DemoCards

### PR DESCRIPTION
**Pull request by johnnychen94**
This tries to build something like http://juliaplots.org/AlgebraOfGraphics.jl/dev/gallery/ using DemoCards.

This uses the [Literate](https://github.com/fredrikekre/Literate.jl) syntax:

- leading `#` means markdown
- leading `##` means Julia comment

Todo:

- [ ] I don't know how to export a PNG file to get the cover image #5
- [ ] I put all demos into one section `Basic`, you might want to split them down into multiple folders

### CODE REVIEW

**Comment by cjdoris** [comment]
Looks nice, thanks! Having the examples as literate .jl files is nice.

As commented on #5, generating thumbnails automatically may be difficult. In the meantime, could we make them by hand?

I'm happy with one section for now - obviously it could be split logically as more get added.

**Comment by johnnychen94** [comment]
> In the meantime, could we make them by hand?

Absolutely, we just need to add a `cover` entry for each file. It's just that usually people generate them on the fly https://github.com/JuliaPlots/AlgebraOfGraphics.jl/blob/16441cf7a507e189c4936fa6e28bf91a4b235aec/docs/gallery/gallery/basic%20visualizations/lines_and_markers.jl#L44-L46

---

Another possible solution is to use PythonCall, if possible.

**Comment by cjdoris** [comment]
Going to merge and tweak things. For now I'll just hand-generate the thumbnails. Thanks very much!

**Comment by johnnychen94** [comment]
Sorry that I forgot this PR the next day 🙈 and thanks for merging it.

I noticed that CI failed to run on the main branch, which is weird. I was able to build it successfully without a single `include("docs/make.jl")`.

**Comment by cjdoris** [comment]
https://cjdoris.github.io/Bokeh.jl/dev/gallery/ 🎨

**Comment by johnnychen94** [comment]
Ohhh it looks so nice!

May I copy and add your style asset to DemoCards for "listbokeh"?

**Comment by cjdoris** [comment]
Yeah sure, use that CSS however you like.

**Comment by RoyiAvital** [comment]
It will be great to a sample code which shows how to use double click for reset (Like clicking the reset button).

A great candidate would be the [Bar Chart](https://cjdoris.github.io/Bokeh.jl/dev/gallery/Basic/vbar/#demo_vbar) example as it has no tool top but panning is active. So it makes sense that double click will reset the figure.

**Pull request merged**
